// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: level.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLevelReq) Reset() {
	*x = GetLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelReq) ProtoMessage() {}

func (x *GetLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelReq.ProtoReflect.Descriptor instead.
func (*GetLevelReq) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{0}
}

func (x *GetLevelReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLevelRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Data *Level `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg  string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetLevelRsp) Reset() {
	*x = GetLevelRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelRsp) ProtoMessage() {}

func (x *GetLevelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelRsp.ProtoReflect.Descriptor instead.
func (*GetLevelRsp) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{1}
}

func (x *GetLevelRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetLevelRsp) GetData() *Level {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetLevelRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Level struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc      string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Level) Reset() {
	*x = Level{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{2}
}

func (x *Level) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Level) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Level) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Level) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLevelListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetLevelListReq) Reset() {
	*x = GetLevelListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelListReq) ProtoMessage() {}

func (x *GetLevelListReq) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelListReq.ProtoReflect.Descriptor instead.
func (*GetLevelListReq) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{3}
}

func (x *GetLevelListReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLevelListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLevelListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLevelListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetLevelListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   int32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Data  []*Level `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Total int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Msg   string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetLevelListRsp) Reset() {
	*x = GetLevelListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelListRsp) ProtoMessage() {}

func (x *GetLevelListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelListRsp.ProtoReflect.Descriptor instead.
func (*GetLevelListRsp) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{4}
}

func (x *GetLevelListRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetLevelListRsp) GetData() []*Level {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetLevelListRsp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLevelListRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddLevelInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Level `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddLevelInfoReq) Reset() {
	*x = AddLevelInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLevelInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLevelInfoReq) ProtoMessage() {}

func (x *AddLevelInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLevelInfoReq.ProtoReflect.Descriptor instead.
func (*AddLevelInfoReq) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{5}
}

func (x *AddLevelInfoReq) GetData() *Level {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddLevelInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddLevelInfoRsp) Reset() {
	*x = AddLevelInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLevelInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLevelInfoRsp) ProtoMessage() {}

func (x *AddLevelInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLevelInfoRsp.ProtoReflect.Descriptor instead.
func (*AddLevelInfoRsp) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{6}
}

func (x *AddLevelInfoRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *AddLevelInfoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DelLevelInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelLevelInfoReq) Reset() {
	*x = DelLevelInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLevelInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLevelInfoReq) ProtoMessage() {}

func (x *DelLevelInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLevelInfoReq.ProtoReflect.Descriptor instead.
func (*DelLevelInfoReq) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{7}
}

func (x *DelLevelInfoReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelLevelInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DelLevelInfoRsp) Reset() {
	*x = DelLevelInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLevelInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLevelInfoRsp) ProtoMessage() {}

func (x *DelLevelInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLevelInfoRsp.ProtoReflect.Descriptor instead.
func (*DelLevelInfoRsp) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{8}
}

func (x *DelLevelInfoRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *DelLevelInfoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateLevelInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Level `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateLevelInfoReq) Reset() {
	*x = UpdateLevelInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLevelInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLevelInfoReq) ProtoMessage() {}

func (x *UpdateLevelInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLevelInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateLevelInfoReq) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLevelInfoReq) GetData() *Level {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLevelInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateLevelInfoRsp) Reset() {
	*x = UpdateLevelInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLevelInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLevelInfoRsp) ProtoMessage() {}

func (x *UpdateLevelInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLevelInfoRsp.ProtoReflect.Descriptor instead.
func (*UpdateLevelInfoRsp) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLevelInfoRsp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *UpdateLevelInfoRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_level_proto protoreflect.FileDescriptor

var file_level_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x1d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5e, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x66, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x6d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x33, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x73, 0x74, 0x75, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_level_proto_rawDescOnce sync.Once
	file_level_proto_rawDescData = file_level_proto_rawDesc
)

func file_level_proto_rawDescGZIP() []byte {
	file_level_proto_rawDescOnce.Do(func() {
		file_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_level_proto_rawDescData)
	})
	return file_level_proto_rawDescData
}

var file_level_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_level_proto_goTypes = []interface{}{
	(*GetLevelReq)(nil),        // 0: level.GetLevelReq
	(*GetLevelRsp)(nil),        // 1: level.GetLevelRsp
	(*Level)(nil),              // 2: level.Level
	(*GetLevelListReq)(nil),    // 3: level.GetLevelListReq
	(*GetLevelListRsp)(nil),    // 4: level.GetLevelListRsp
	(*AddLevelInfoReq)(nil),    // 5: level.AddLevelInfoReq
	(*AddLevelInfoRsp)(nil),    // 6: level.AddLevelInfoRsp
	(*DelLevelInfoReq)(nil),    // 7: level.DelLevelInfoReq
	(*DelLevelInfoRsp)(nil),    // 8: level.DelLevelInfoRsp
	(*UpdateLevelInfoReq)(nil), // 9: level.UpdateLevelInfoReq
	(*UpdateLevelInfoRsp)(nil), // 10: level.UpdateLevelInfoRsp
}
var file_level_proto_depIdxs = []int32{
	2, // 0: level.GetLevelRsp.data:type_name -> level.Level
	2, // 1: level.GetLevelListRsp.data:type_name -> level.Level
	2, // 2: level.AddLevelInfoReq.data:type_name -> level.Level
	2, // 3: level.UpdateLevelInfoReq.data:type_name -> level.Level
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_level_proto_init() }
func file_level_proto_init() {
	if File_level_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_level_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Level); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLevelInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLevelInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLevelInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLevelInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLevelInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLevelInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_level_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_level_proto_goTypes,
		DependencyIndexes: file_level_proto_depIdxs,
		MessageInfos:      file_level_proto_msgTypes,
	}.Build()
	File_level_proto = out.File
	file_level_proto_rawDesc = nil
	file_level_proto_goTypes = nil
	file_level_proto_depIdxs = nil
}
