// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: level_if.proto

package stub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LevelServiceClient is the client API for LevelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LevelServiceClient interface {
	//获取等级信息
	GetLevel(ctx context.Context, in *GetLevelReq, opts ...grpc.CallOption) (*GetLevelRsp, error)
	//获取等级列表
	GetLevelList(ctx context.Context, in *GetLevelListReq, opts ...grpc.CallOption) (*GetLevelListRsp, error)
	//新增等级信息
	AddLevelInfo(ctx context.Context, in *AddLevelInfoReq, opts ...grpc.CallOption) (*AddLevelInfoRsp, error)
	//删除等级信息
	DelLevelInfo(ctx context.Context, in *DelLevelInfoReq, opts ...grpc.CallOption) (*DelLevelInfoRsp, error)
	//更新等级信息
	UpdateLevelInfo(ctx context.Context, in *UpdateLevelInfoReq, opts ...grpc.CallOption) (*UpdateLevelInfoRsp, error)
}

type levelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLevelServiceClient(cc grpc.ClientConnInterface) LevelServiceClient {
	return &levelServiceClient{cc}
}

func (c *levelServiceClient) GetLevel(ctx context.Context, in *GetLevelReq, opts ...grpc.CallOption) (*GetLevelRsp, error) {
	out := new(GetLevelRsp)
	err := c.cc.Invoke(ctx, "/level.LevelService/GetLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelServiceClient) GetLevelList(ctx context.Context, in *GetLevelListReq, opts ...grpc.CallOption) (*GetLevelListRsp, error) {
	out := new(GetLevelListRsp)
	err := c.cc.Invoke(ctx, "/level.LevelService/GetLevelList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelServiceClient) AddLevelInfo(ctx context.Context, in *AddLevelInfoReq, opts ...grpc.CallOption) (*AddLevelInfoRsp, error) {
	out := new(AddLevelInfoRsp)
	err := c.cc.Invoke(ctx, "/level.LevelService/AddLevelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelServiceClient) DelLevelInfo(ctx context.Context, in *DelLevelInfoReq, opts ...grpc.CallOption) (*DelLevelInfoRsp, error) {
	out := new(DelLevelInfoRsp)
	err := c.cc.Invoke(ctx, "/level.LevelService/DelLevelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelServiceClient) UpdateLevelInfo(ctx context.Context, in *UpdateLevelInfoReq, opts ...grpc.CallOption) (*UpdateLevelInfoRsp, error) {
	out := new(UpdateLevelInfoRsp)
	err := c.cc.Invoke(ctx, "/level.LevelService/UpdateLevelInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LevelServiceServer is the server API for LevelService service.
// All implementations must embed UnimplementedLevelServiceServer
// for forward compatibility
type LevelServiceServer interface {
	//获取等级信息
	GetLevel(context.Context, *GetLevelReq) (*GetLevelRsp, error)
	//获取等级列表
	GetLevelList(context.Context, *GetLevelListReq) (*GetLevelListRsp, error)
	//新增等级信息
	AddLevelInfo(context.Context, *AddLevelInfoReq) (*AddLevelInfoRsp, error)
	//删除等级信息
	DelLevelInfo(context.Context, *DelLevelInfoReq) (*DelLevelInfoRsp, error)
	//更新等级信息
	UpdateLevelInfo(context.Context, *UpdateLevelInfoReq) (*UpdateLevelInfoRsp, error)
	mustEmbedUnimplementedLevelServiceServer()
}

// UnimplementedLevelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLevelServiceServer struct {
}

func (UnimplementedLevelServiceServer) GetLevel(context.Context, *GetLevelReq) (*GetLevelRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevel not implemented")
}
func (UnimplementedLevelServiceServer) GetLevelList(context.Context, *GetLevelListReq) (*GetLevelListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevelList not implemented")
}
func (UnimplementedLevelServiceServer) AddLevelInfo(context.Context, *AddLevelInfoReq) (*AddLevelInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLevelInfo not implemented")
}
func (UnimplementedLevelServiceServer) DelLevelInfo(context.Context, *DelLevelInfoReq) (*DelLevelInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelLevelInfo not implemented")
}
func (UnimplementedLevelServiceServer) UpdateLevelInfo(context.Context, *UpdateLevelInfoReq) (*UpdateLevelInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLevelInfo not implemented")
}
func (UnimplementedLevelServiceServer) mustEmbedUnimplementedLevelServiceServer() {}

// UnsafeLevelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LevelServiceServer will
// result in compilation errors.
type UnsafeLevelServiceServer interface {
	mustEmbedUnimplementedLevelServiceServer()
}

func RegisterLevelServiceServer(s grpc.ServiceRegistrar, srv LevelServiceServer) {
	s.RegisterService(&LevelService_ServiceDesc, srv)
}

func _LevelService_GetLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServiceServer).GetLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.LevelService/GetLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServiceServer).GetLevel(ctx, req.(*GetLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevelService_GetLevelList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLevelListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServiceServer).GetLevelList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.LevelService/GetLevelList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServiceServer).GetLevelList(ctx, req.(*GetLevelListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevelService_AddLevelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLevelInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServiceServer).AddLevelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.LevelService/AddLevelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServiceServer).AddLevelInfo(ctx, req.(*AddLevelInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevelService_DelLevelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelLevelInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServiceServer).DelLevelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.LevelService/DelLevelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServiceServer).DelLevelInfo(ctx, req.(*DelLevelInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LevelService_UpdateLevelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLevelInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServiceServer).UpdateLevelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.LevelService/UpdateLevelInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServiceServer).UpdateLevelInfo(ctx, req.(*UpdateLevelInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LevelService_ServiceDesc is the grpc.ServiceDesc for LevelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LevelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "level.LevelService",
	HandlerType: (*LevelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLevel",
			Handler:    _LevelService_GetLevel_Handler,
		},
		{
			MethodName: "GetLevelList",
			Handler:    _LevelService_GetLevelList_Handler,
		},
		{
			MethodName: "AddLevelInfo",
			Handler:    _LevelService_AddLevelInfo_Handler,
		},
		{
			MethodName: "DelLevelInfo",
			Handler:    _LevelService_DelLevelInfo_Handler,
		},
		{
			MethodName: "UpdateLevelInfo",
			Handler:    _LevelService_UpdateLevelInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "level_if.proto",
}
